import { writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import swaggerJsdoc from 'swagger-jsdoc';

const __dirname = dirname(fileURLToPath(import.meta.url));

const options: swaggerJsdoc.Options = {
    definition: {
        openapi: '3.0.0',
        info: {
            title: 'NebulaX API',
            version: '1.0.0',
            description: 'API documentation for NebulaX backend',
        },
        servers: [{ url: '/', description: 'Current host' }],
        components: {
            securitySchemes: {
                cookieAuth: {
                    type: 'apiKey',
                    in: 'cookie',
                    name: 'token',
                },
            },
            schemas: {
                User: {
                    type: 'object',
                    properties: {
                        id: { type: 'integer' },
                        username: { type: 'string' },
                        name: { type: 'string' },
                        email: { type: 'string', format: 'email' },
                        avatar_color_id: { type: 'integer', nullable: true },
                        about: { type: 'string', nullable: true },
                    },
                },
                Room: {
                    type: 'object',
                    properties: {
                        id: { type: 'integer' },
                        name: { type: 'string' },
                        description: { type: 'string', nullable: true },
                        theme_id: { type: 'integer', nullable: true },
                        created_at: { type: 'string', format: 'date-time' },
                    },
                },
                Tag: {
                    type: 'object',
                    properties: {
                        id: { type: 'integer' },
                        name: { type: 'string' },
                    },
                },
                Error: {
                    type: 'object',
                    properties: {
                        message: { type: 'string' },
                    },
                },
            },
        },
        security: [{ cookieAuth: [] }],
    },
    apis: ['./docs/*.swagger.ts'],
};

const swaggerSpec = swaggerJsdoc(options);

const outFile = join(__dirname, '../src/config/swagger.generated.ts');

const banner = '// AUTO-GENERATED by scripts/generate-swagger.ts — do not edit by hand.\n// Run `npm run docs:generate` to refresh after changing route @openapi comments.\n';

writeFileSync(outFile, `${banner}export const swaggerSpec = ${JSON.stringify(swaggerSpec, null, 2)};\n`);

console.log(`Swagger spec written to ${outFile}`);
